import USER from './user.svg'
import LOADER from './loader.svg'
import SUCCESS from './success.svg'
import WARNING_ICON from './exclaimation-circle.svg'
import OTP_IMAGE from './otp_icon.svg'
import INFO_CIRCLE from './info-circle.svg'
import CLOSE_INFO from './info_close.svg'
import NAVIGATION_ICON from './back_button.svg'
import VENDOR_MARKER from './marker.svg'
import CUSTOMER_MARKER from './customer_location_marker.svg'
import CANCEL_ICON from './cancel (1).svg'
import PLUS_ICON from './plus.svg'
import CYLINDER from './gas_cylinder.svg'
import SHOPPING_BAG from './shopping bag.svg'
import INCREASE_ORDER_ICON from './pluss.svg'
import DECREASE_ORDER_ICON from './minus.svg'
import CARD_ICON from './card.svg'
import CHECKBOX_ICON from './check_box_outline_blank.svg'
import LOCATION_ICON from './location_on.svg'
import RIGHT_ICON from './chevron_left.svg'
import ALMOST_DONE from './almost_done_loader.svg'
import CHECKED from './check.svg'
import AVATAR from './avatar.svg'
import LOGIN from './uil_signin.svg'
import NAVIGATOR from './back_button.svg'
import CART from './cart.svg'

export {USER,LOADER,SUCCESS,WARNING_ICON,OTP_IMAGE,INFO_CIRCLE,CLOSE_INFO,NAVIGATION_ICON,VENDOR_MARKER,CUSTOMER_MARKER,CANCEL_ICON,PLUS_ICON,CYLINDER,SHOPPING_BAG,INCREASE_ORDER_ICON,DECREASE_ORDER_ICON,CARD_ICON,CHECKBOX_ICON, LOCATION_ICON,RIGHT_ICON,ALMOST_DONE,CHECKED,AVATAR,LOGIN,NAVIGATOR,CART}
